---
- name: Check the importing of variables
  hosts: all
  become: true

  tasks:
    - name: Debug to see if import was successful
      debug:
        msg: "Testing variables: {{ server }}"

    - name: Install Apache
      apt:
        name: "{{ server }}"
        state: present
        update_cache: true

    - name: Start and Enable Apache
      service:
        name: "{{ server }}"
        state: started
        enabled: true

    - name: Edit index file
      copy:
        content: "Hey there! This is {{ server }}"
        dest: /var/www/html/index.html